version: '2'
services:
        nginx:
                build: './nginx'
                ports:
                 - 9000:80
                networks:
                 - se_backend
        grproxy:
                depends_on:
                 - nginx
                 - gserve1
                 - gserve2
                build: './grproxy'
                ports:
                 - 80:8080
                 - 8080:8080 
                networks:
                 - se_frontend
                 - se_backend
        hbase: 
                build: './hbase'
                networks:
                  se_backend:
                   aliases:
                   - zookeeper

        gserve1:
                depends_on:
                 - hbase
                build: './gserve'
                environment:
                 - gsname=gserve1
                networks:
                 - se_backend
        gserve2:
                depends_on:
                 - hbase
                build: './gserve'
                environment:
                 - gsname=gserve2
                networks:
                 - se_backend

networks:
        se_backend:
        se_frontend:

