version: '2'
services:
        nginx:
                build: './nginx'
                ports:
                 - 8080:80
                networks:
                 - se_backend
#       grproxy:
#       hbase:
#       gserve1:
#       gserve2:

networks:
        se_backend:
        se_frontend:

