version: '2'
services:
        nginx:
                build: './nginx'
                ports:
                 - 9000:80
                networks:
                 - se_backend
        grproxy:
                build: './grproxy'
                ports:
                 - 8080:8080
                networks:
                 - se_frontend
                 - se_backend
        hbase: 
                build: './hbase'
                networks:
                  se_backend:
                   aliases:
                   - zookeper

#       gserve1:
#       gserve2:

networks:
        se_backend:
        se_frontend:

