version: '2'
services:
        nginx:
                build: './nginx'
                ports:
                 - 9000:80
                networks:
                 - se_backend
        grproxy:
                depends_on:
                 - nginx
                 - gserve1
                 - gserve2
                build: './grproxy'
                ports:
                 - 8080:8080
                networks:
                 - se_frontend
                 - se_backend
        hbase: 
                build: './hbase'
                networks:
                  se_backend:
                   aliases:
                   - zookeper

        gserve1:
                build: './gserve'
                networks:
                 - se_backend
        gserve2:
                build: './gserve'
                networks:
                 - se_backend

networks:
        se_backend:
        se_frontend:

